# Generated by Django 3.2.25 on 2025-09-09 20:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AudioFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название аудиофайла')),
                ('path', models.CharField(blank=True, max_length=500, null=True, verbose_name='Путь к файлу в хранилище')),
                ('storage_url', models.URLField(blank=True, null=True, verbose_name='Ссылка на файл в хранилище')),
                ('duration_seconds', models.FloatField(blank=True, null=True, verbose_name='Длительность (в секундах)')),
                ('extension', models.CharField(blank=True, max_length=20, null=True, verbose_name='Расширение файла')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Время начала обработки')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='Время окончания обработки')),
            ],
        ),
        migrations.CreateModel(
            name='Integration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint', models.CharField(blank=True, max_length=255, null=True, verbose_name='Endpoint')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
        ),
        migrations.CreateModel(
            name='VideoFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Оригинальное название видео')),
                ('title_saved', models.CharField(blank=True, max_length=255, null=True, verbose_name='Системное имя файла')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Время загрузки')),
                ('duration_seconds', models.FloatField(blank=True, null=True, verbose_name='Длительность (в секундах)')),
                ('extension', models.CharField(blank=True, max_length=20, null=True, verbose_name='Расширение файла')),
                ('storage_url', models.URLField(blank=True, null=True, verbose_name='Ссылка на файл в хранилище')),
            ],
        ),
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_custom', models.BooleanField(default=False, verbose_name='Пользовательский шаблон')),
                ('text', models.TextField(blank=True, null=True, verbose_name='Текст шаблона')),
                ('integration', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.integration', verbose_name='Интеграция')),
            ],
        ),
        migrations.CreateModel(
            name='MediaTransformer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transcribation', models.TextField(blank=True, null=True, verbose_name='Текст транскрибации')),
                ('gpt_result', models.TextField(blank=True, null=True, verbose_name='Результат анализа GPT')),
                ('audio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.audiofile', verbose_name='Аудио')),
                ('integration', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.integration', verbose_name='Интеграция')),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.template', verbose_name='Шаблон')),
                ('video', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.videofile', verbose_name='Видео')),
            ],
        ),
    ]
