# Generated by Django 3.2.25 on 2025-09-11 19:35

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_uploaded_title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Оригинальное название видео')),
                ('video_title_saved', models.CharField(blank=True, max_length=255, null=True, verbose_name='Системное имя видео')),
                ('video_local_uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Время загрузки видео в Сервис iCast')),
                ('duration_seconds', models.FloatField(blank=True, null=True, verbose_name='Длительность видео (в секундах)')),
                ('extension', models.CharField(blank=True, max_length=20, null=True, verbose_name='Расширение видеофайла')),
                ('storage_url', models.URLField(blank=True, null=True, verbose_name='Ссылка на видеофайл в хранилище Яндекс')),
                ('integration', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.integration', verbose_name='Интеграция')),
            ],
        ),
        migrations.AddField(
            model_name='videofile',
            name='integration',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.integration', verbose_name='Интеграция'),
        ),
        migrations.CreateModel(
            name='OutboxEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('document_created', 'Документ создан'), ('case_synced', 'Синхронизация дела'), ('email_sent', 'Email отправлен'), ('webhook_triggered', 'Вебхук вызван')], max_length=64, verbose_name='Тип события')),
                ('payload', models.JSONField(verbose_name='Полезная нагрузка (например, путь к файлу, результат анализа и т.д.)')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Когда событие создано')),
                ('processed', models.BooleanField(default=False, verbose_name='Обработано?')),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='Когда событие было обработано')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='Сообщение об ошибке (если было)')),
                ('media_task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outbox_events', to='core.mediatask', verbose_name='Источник события (MediaTask)')),
            ],
            options={
                'verbose_name': 'Outbox-событие',
                'verbose_name_plural': 'Outbox-события',
                'ordering': ['created_at'],
            },
        ),
    ]
