# Generated by Django 3.2.25 on 2025-09-13 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20250911_2235'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mediatransformer',
            name='audio',
        ),
        migrations.RemoveField(
            model_name='mediatransformer',
            name='integration',
        ),
        migrations.RemoveField(
            model_name='mediatransformer',
            name='template',
        ),
        migrations.RemoveField(
            model_name='mediatransformer',
            name='video',
        ),
        migrations.RemoveField(
            model_name='videofile',
            name='integration',
        ),
        migrations.AlterField(
            model_name='outboxevent',
            name='event_type',
            field=models.CharField(choices=[('video_uploaded', 'Видео загружено'), ('video_uploaded_yandex', 'Видео загружено в хранилище Яндекс'), ('document_created', 'Документ создан'), ('case_synced', 'Синхронизация дела'), ('email_sent', 'Email отправлен'), ('webhook_triggered', 'Вебхук вызван')], max_length=64, verbose_name='Тип события'),
        ),
        migrations.DeleteModel(
            name='AudioFile',
        ),
        migrations.DeleteModel(
            name='MediaTransformer',
        ),
        migrations.DeleteModel(
            name='VideoFile',
        ),
    ]
