# Generated by Django 3.2.25 on 2025-09-13 20:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20250913_1711'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediatask',
            name='audio_duration_seconds',
            field=models.FloatField(blank=True, null=True, verbose_name='Длительность аудио (в секундах)'),
        ),
        migrations.AddField(
            model_name='mediatask',
            name='audio_extension_uploaded',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Расширение загруженного аудиофайла'),
        ),
        migrations.AddField(
            model_name='mediatask',
            name='audio_local_uploaded_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Время загрузки аудио в Сервис iCast'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mediatask',
            name='audio_storage_url',
            field=models.URLField(blank=True, null=True, verbose_name='Ссылка на аудио в хранилище Яндекс'),
        ),
        migrations.AddField(
            model_name='mediatask',
            name='audio_title_saved',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Системное имя аудио'),
        ),
        migrations.AddField(
            model_name='mediatask',
            name='audio_uploaded_title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Оригинальное название аудио'),
        ),
    ]
