# Generated by Django 3.2.25 on 2025-09-13 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20250913_2319'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mediatask',
            old_name='extension',
            new_name='video_extension',
        ),
    ]
