# Generated by Django 3.2.25 on 2025-09-13 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_rename_extension_mediatask_video_extension'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mediatask',
            old_name='storage_url',
            new_name='video_storage_url',
        ),
    ]
