# Generated by Django 3.2.25 on 2025-09-13 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_outboxevent_event_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outboxevent',
            name='event_type',
            field=models.CharField(choices=[('video_uploaded', 'Видео загружено'), ('video_uploaded_yandex', 'Видео загружено в хранилище Яндекс'), ('audio_wav_uploaded', 'Аудио WAV загружено'), ('audio_send_to_yandex', 'Аудио отправлено в хранилище Яндекс'), ('document_created', 'Документ создан'), ('case_synced', 'Синхронизация дела'), ('email_sent', 'Email отправлен'), ('webhook_triggered', 'Вебхук вызван')], max_length=64, verbose_name='Тип события'),
        ),
    ]
