# Generated by Django 3.2.25 on 2025-09-14 12:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20250914_1539'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='outboxevent',
            name='audio_duration_seconds',
        ),
        migrations.RemoveField(
            model_name='outboxevent',
            name='diarization_segments',
        ),
        migrations.RemoveField(
            model_name='outboxevent',
            name='diarization_text',
        ),
        migrations.RemoveField(
            model_name='outboxevent',
            name='nexara_completed_at',
        ),
        migrations.RemoveField(
            model_name='outboxevent',
            name='nexara_error',
        ),
        migrations.RemoveField(
            model_name='outboxevent',
            name='nexara_requested_at',
        ),
        migrations.RemoveField(
            model_name='outboxevent',
            name='nexara_status',
        ),
        migrations.AddField(
            model_name='mediatask',
            name='diarization_segments',
            field=models.JSONField(blank=True, help_text='Массив сегментов из Nexara (speaker, start, end, text).', null=True, verbose_name='Сегменты диаризации'),
        ),
        migrations.AddField(
            model_name='mediatask',
            name='diarization_text',
            field=models.TextField(blank=True, help_text='Склеенный текст всех сегментов.', null=True, verbose_name='Полный текст после диаризации'),
        ),
        migrations.AddField(
            model_name='mediatask',
            name='nexara_completed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Когда Nexara вернула результат'),
        ),
        migrations.AddField(
            model_name='mediatask',
            name='nexara_error',
            field=models.TextField(blank=True, help_text='Сохраняем ответ об ошибке, если запрос неудачный', null=True, verbose_name='Текст ошибки Nexara'),
        ),
        migrations.AddField(
            model_name='mediatask',
            name='nexara_requested_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Когда был отправлен запрос в Nexara'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mediatask',
            name='nexara_status',
            field=models.CharField(choices=[('pending', 'В очереди'), ('processing', 'Обработка'), ('done', 'Готово'), ('error', 'Ошибка')], default='pending', max_length=20, verbose_name='Статус обработки Nexara'),
        ),
        migrations.AlterField(
            model_name='mediatask',
            name='audio_duration_seconds',
            field=models.FloatField(blank=True, null=True, verbose_name='Фактическая длительность аудио (по Nexara)'),
        ),
    ]
