# Generated by Django 3.2.25 on 2025-09-14 13:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_outboxevent_event_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='CastTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questions', models.JSONField(blank=True, null=True, verbose_name='Вопросы (JSON)')),
                ('template_type', models.CharField(choices=[('jtbd', 'JTBD'), ('score', 'Score'), ('custom', 'Custom')], default='custom', max_length=20, verbose_name='Тип шаблона')),
                ('integration', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.integration', verbose_name='Интеграция')),
            ],
        ),
        migrations.AddField(
            model_name='mediatask',
            name='cast_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='media_tasks', to='core.casttemplate', verbose_name='Шаблон обработки'),
        ),
    ]
