# Generated by Django 3.2.25 on 2025-09-14 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20250914_1655'),
    ]

    operations = [
        migrations.AddField(
            model_name='casttemplate',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Template Title'),
        ),
    ]
