# Generated by Django 3.2.25 on 2025-09-14 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_casttemplate_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='casttemplate',
            name='help_text',
            field=models.TextField(blank=True, help_text='Описание шаблона.', null=True, verbose_name='Полный текст после диаризации'),
        ),
    ]
