# Generated by Django 3.2.25 on 2025-09-14 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_mediatask_gpt_result'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediatask',
            name='gpt_raw_response',
            field=models.TextField(blank=True, null=True, verbose_name='Сырой ответ GPT'),
        ),
    ]
