# Generated by Django 3.2.25 on 2025-09-16 19:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_mediatask_gpt_raw_response'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediatask',
            name='audio_duration_seconds_nexara',
            field=models.FloatField(blank=True, null=True, verbose_name='Фактическая длительность аудио (по Nexara)'),
        ),
        migrations.AddField(
            model_name='mediatask',
            name='status',
            field=models.CharField(choices=[('loaded', 'Загружен'), ('transcribation', 'Транскрибация выполняется'), ('data_extraction', 'Извлечение данных выполняется'), ('success', 'Успешно завершено'), ('failed', 'Ошибка')], default='loaded', max_length=32, verbose_name='Статус задачи'),
        ),
        migrations.AlterField(
            model_name='mediatask',
            name='audio_duration_seconds',
            field=models.FloatField(blank=True, null=True, verbose_name='Длительность аудио (в секундах)'),
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_title', models.CharField(max_length=255, verbose_name='Название проекта')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание проекта')),
                ('integration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='core.integration', verbose_name='Интеграция')),
            ],
        ),
        migrations.AddField(
            model_name='mediatask',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='media_tasks', to='core.project', verbose_name='Проект'),
        ),
    ]
