# Generated by Django 3.2.25 on 2025-09-18 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_auto_20250916_2227'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediatask',
            name='excel_path',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Путь к Excel в хранилище'),
        ),
        migrations.AddField(
            model_name='mediatask',
            name='finished_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата и время завершения'),
        ),
        migrations.AddField(
            model_name='mediatask',
            name='pdf_path',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Путь к PDF в хранилище'),
        ),
        migrations.AddField(
            model_name='mediatask',
            name='token_count',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Количество токенов'),
        ),
        migrations.AddField(
            model_name='mediatask',
            name='total_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Итоговая цена'),
        ),
        migrations.AddField(
            model_name='mediatask',
            name='transcribation_path',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Путь к транскрипции в хранилище'),
        ),
    ]
