# Generated by Django 3.2.25 on 2025-09-24 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_alter_outboxevent_event_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='casttemplate',
            name='promt_text',
            field=models.TextField(blank=True, help_text='Промт для запроса', null=True, verbose_name='Текст промта'),
        ),
    ]
