# Generated by Django 3.2.25 on 2025-10-03 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_casttemplate_promt_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outboxevent',
            name='event_type',
            field=models.CharField(choices=[('video_uploaded', 'Видео загружено'), ('video_uploaded_yandex', 'Видео загружено в хранилище Яндекс'), ('audio_uploaded_to_yandex', 'Аудио загружено в хранилище Яндекс'), ('audio_wav_uploaded', 'Аудио WAV загружено'), ('audio_send_to_yandex', 'Аудио отправлено в хранилище Яндекс'), ('audio_transcribe_started', 'Транскрибация аудио начата'), ('audio_transcribation_ready', 'Транскрибация успешно завершена'), ('template_selected', 'Шаблон выбран'), ('gpt_result_ready', 'Результат GPT готов'), ('excel_file_saved_to_yandex', 'Файл Excel загружен в Яндекс хранилище'), ('document_created', 'Документ создан'), ('case_synced', 'Синхронизация дела'), ('email_sent', 'Email отправлен'), ('webhook_triggered', 'Вебхук вызван')], max_length=64, verbose_name='Тип события'),
        ),
    ]
