# Generated by Django 3.2.25 on 2025-10-03 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_alter_outboxevent_event_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='casttemplate',
            name='default',
            field=models.BooleanField(default=False, verbose_name='Базовый шаблон'),
        ),
    ]
