# Generated by Django 3.2.25 on 2025-10-05 18:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_casttemplate_default'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediatask',
            name='status',
            field=models.CharField(choices=[('loaded', 'Загружен'), ('process_transcribation', 'Транскрибация выполняется'), ('process_data_extraction', 'Извлечение данных выполняется'), ('data_extraction_success', 'Извлечение данных успешно выполнено'), ('save_excel_start', 'Начало формирования Excel-отчета'), ('save_excel_finish', 'Excel-отчет успешно сформирован'), ('success', 'Успешно завершено'), ('failed', 'Ошибка')], default='loaded', max_length=32, verbose_name='Статус задачи'),
        ),
        migrations.CreateModel(
            name='IntegrationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload_mode', models.CharField(choices=[('full', 'Full'), ('parts', 'Parts')], default='full', max_length=10, verbose_name='Режим загрузки')),
                ('integration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='core.integration', verbose_name='Интеграция')),
            ],
        ),
    ]
