# Generated by Django 3.2.25 on 2025-10-05 18:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_auto_20251005_2117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='integrationsettings',
            name='integration',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='core.integration'),
        ),
    ]
