# Generated by Django 3.2.25 on 2025-10-06 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_alter_integrationsettings_integration'),
    ]

    operations = [
        migrations.AddField(
            model_name='casttemplate',
            name='excel_storage_url',
            field=models.URLField(blank=True, null=True, verbose_name='Ссылка на Excel-шаблон в хранилище Яндекс'),
        ),
        migrations.AddField(
            model_name='casttemplate',
            name='promt',
            field=models.TextField(blank=True, help_text='Промт', null=True, verbose_name='Промт'),
        ),
    ]
