# Generated by Django 3.2.25 on 2025-10-06 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_auto_20251006_2319'),
    ]

    operations = [
        migrations.AddField(
            model_name='casttemplate',
            name='excel_file',
            field=models.FileField(blank=True, help_text='Файл Excel с вопросами (будет обработан автоматически позже).', null=True, upload_to='uploads/templates/', verbose_name='Excel-файл шаблона'),
        ),
    ]
