# Generated by Django 3.2.25 on 2025-10-11 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_casttemplate_excel_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediatask',
            name='audio_local_storage',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Путь к аудиофайлу на локальном сервере'),
        ),
    ]
